version: '3.8'

services:
  cliente_app:
    build:
      context: ./docker/php
    container_name: cliente_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - laravel_mysql
    networks:
      - laravel_red_2025

  cliente_nginx:
    image: nginx:latest
    container_name: cliente_nginx
    restart: always
    ports:
      - "81:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cliente_app
    networks:
      - laravel_red_2025

  cliente_node:
    image: node:22
    container_name: cliente_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: bash -c "npm install && npm run dev"
    ports:
      - "5174:5173"
    networks:
      - laravel_red_2025

  cliente_composer:
    build:
      context: ./docker/php
    container_name: cliente_composer
    working_dir: /var/www
    volumes:
      - .:/var/www
    entrypoint: ["composer"]
    networks:
      - laravel_red_2025

networks:
  laravel_red_2025:
    external: true